-- GENERAL CHALLENGE FOR WHAT I HAVE LEARNT SECTION 1 OF THE COURSE 
-- 1. ALL PAYMENTS GREATER THAN 5 DOLLARS 
SELECT * FROM payment;
SELECT COUNT(*) FROM payment WHERE amount > 5;

-- 2. ALL ACTORS WHOSE NAME STARTS WITH LETTER P
SELECT COUNT(*) FROM actor WHERE first_name ILIKE 'P%';

-- 3. UNIQUE DISTRICTS OF OUR CUSTOMERS 
SELECT COUNT(DISTINCT district) FROM address ; 

-- 4 SAME BUTT NAME 
SELECT DISTINCT district FROM address ; 

--5 FILMS WITH RATING R AND REPLACEMENT COST BETWEEN. 5 AND 15 
SELECT COUNT(*) FROM film 
WHERE rating = 'R' AND replacement_cost
Between 5 and 15;

--6 WORD TRUMAN IN THE TITLE. 
SELECT COUNT(*) FROM film WHERE title ILIKE '%truman%';
